# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: heimauto2020
name: os_software
version: 0.1.0
readme: README.md
authors:
  - heimauto2020 (github.com/heimauto2020)
description: myAnsible ansible_os_software role
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - debian
  - apt
  - pip
repository: https://github.com/heimauto2020/ansible_os_software
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/heimauto2020/ansible_os_software
issues: https://github.com/heimauto2020/ansible_os_software/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
