---
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes 

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Autoremove for no Error while Update
      apt: autoremove=true force_apt_get=yes 
